name: Integral system analyzer

on:
  schedule:
    - cron: "0 2,10,18 * * *"

env:
  FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
  FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
  INTEGRAL_SYSTEM_ANALYSIS_ASYNC: ${{ vars.INTEGRAL_SYSTEM_ANALYSIS_ASYNC }}
  INTEGRAL_SYSTEM_ANALYSIS_AUTOSAVE_EVERY: ${{ vars.INTEGRAL_SYSTEM_ANALYSIS_AUTOSAVE_EVERY }}
  LOGGER_SHOW_THREAD_INFO: ${{ vars.LOGGER_SHOW_THREAD_INFO }}
  RESOURCES_INTEGRAL_SYSTEM_ANALYSIS_FOLDER: 'integralSystemsAnalysis'
  TASKS_MAX_PARALLEL: ${{ vars.INTEGRAL_SYSTEM_ANALYSIS_JOB_TASKS_MAX_PARALLEL }}
  TIMEOUT: ${{ vars.INTEGRAL_SYSTEM_ANALYSIS_JOB_TIMEOUT }}

jobs:
   
  launch-integral-system-indexer:
    name: Launch indexer on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [21]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        env:
          #value 0: reset
          #value 1: index
          INDEX_MODE: '1'
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml
       
  launch-integral-system-analyzer:
    name: Launch analyzer on (JVM ${{ matrix.java }}, ${{ matrix.os }})
    needs: [launch-integral-system-indexer]
    strategy:
      fail-fast: false
#      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        java: [11,11,11,11,11,11,17,17,17,17,17,17,17,21,21,21,21,21,21,21]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and launch
        run: mvn -B compile exec:java -P integral-system-analysis --file pom.xml